// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHPMuWxmc6KmUjUNNMnUE8_MoIgsNbGY0',
    appId: '1:982870762985:web:dcdb56e613683f06fed778',
    messagingSenderId: '982870762985',
    projectId: 'proyek-flutter-80d84',
    authDomain: 'proyek-flutter-80d84.firebaseapp.com',
    storageBucket: 'proyek-flutter-80d84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGx3opWEKEAUBmGLYtmkogkh8bPJqt3T0',
    appId: '1:982870762985:android:e3228149451662a8fed778',
    messagingSenderId: '982870762985',
    projectId: 'proyek-flutter-80d84',
    storageBucket: 'proyek-flutter-80d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtL9E-e11yKJY2xAEa9o1lb-X-UqWLjo',
    appId: '1:982870762985:ios:ed9677d2bd271155fed778',
    messagingSenderId: '982870762985',
    projectId: 'proyek-flutter-80d84',
    storageBucket: 'proyek-flutter-80d84.firebasestorage.app',
    iosBundleId: 'com.example.proyekflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhtL9E-e11yKJY2xAEa9o1lb-X-UqWLjo',
    appId: '1:982870762985:ios:ed9677d2bd271155fed778',
    messagingSenderId: '982870762985',
    projectId: 'proyek-flutter-80d84',
    storageBucket: 'proyek-flutter-80d84.firebasestorage.app',
    iosBundleId: 'com.example.proyekflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHPMuWxmc6KmUjUNNMnUE8_MoIgsNbGY0',
    appId: '1:982870762985:web:04d90e46713abdaafed778',
    messagingSenderId: '982870762985',
    projectId: 'proyek-flutter-80d84',
    authDomain: 'proyek-flutter-80d84.firebaseapp.com',
    storageBucket: 'proyek-flutter-80d84.firebasestorage.app',
  );
}
